### ISSUE TITLE
遊び方の表示

### ISSUE THREAD

**Issue by YukaChoco** [syota-kawaguchi/SpinoCup202409_d#35]

**Comment by kinjo1130** [comment]
[![Image from Gyazo](https://i.gyazo.com/c76c7aa2d56955b727472014dd824600.jpg)](https://gyazo.com/c76c7aa2d56955b727472014dd824600)

こんな感じで実装しておきました！

**Comment by kinjo1130** [comment]
deploy済みなんで、closeします
